### ISSUE TITLE
Game Crashes on loading in to a World

### ISSUE THREAD

**Issue by MrLoLf** [TeamMidnightDust/MidnightControls#134]
**Describe the bug**
The Game crashes on loading in to it

**To Reproduce**
1. have controller already pluged in but not active
2. Go to single player
3.  wait a sec and move the mouse
4. See minecraft not loading -> error

**Expected behavior**
The world loads normal and the game doesn't crash

**Screenshots**
Can#t be provided due to instantly crashing

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft 1.19.2 - Fabric API 0.62.0+1.19.2 -Fabric Loader 0.14.10
 - Mods see mod list of [Roughly Clientsided](https://www.curseforge.com/minecraft/modpacks/roughly-clientsided)
 - Version 1.6.0+1.19
 - Branch stable? from Curseforge the newest Release

**Additional context**
java.lang.NullPointerException: Cannot invoke "eu.midnightdust.midnightcontrols.client.MidnightControlsClient.onMcInit(net.minecraft.class_310)" because the return value of "eu.midnightdust.midnightcontrols.client.MidnightControlsClient.get()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.4)
	at net.minecraft.client.MinecraftClient.handler$dfm018$onInit(MinecraftClient:19502)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:670)
	at net.minecraft.client.main.Main.main(Main:205)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Motschen** [comment]
Could you please remove Not Enough Crashes from your mod folder and send me the full log? That'd help me find the root cause of the issue, it's likely a mod conflict.

**Comment by Motschen** [comment]
Also, you're using a outdated version of the mod, maybe that could be causing the crash.

**Comment by MrLoLf** [comment]
Nvm. this was an old error log I had, the new one doesn't seem to have something to do with Midnight Controls. Sorry for the false error report and thanks for your help.
